### ISSUE TITLE
Add-day always downloads input for day 14 from 2015

### ISSUE THREAD

**Issue by maxrdu** [marcelblijleven/adventofcode#8]
When trying out your setup it seems like everytime `add-day` is run, instead of the input for the specified day, it downloads the input of day 14 from 2015.
This is caused when the input does not exist because it's hard coded into the except case.
https://github.com/marcelblijleven/adventofcode/blob/fa50425638de6ee79b1ec72ab09a26c9d712129e/src/adventofcode/scripts/add_day.py#L36-L40

**Comment by marcelblijleven** [comment]
Thanks for noticing, I noticed it this morning when starting with 2021. Just pushed the fix
